---
# Main playbook for Ubuntu Desktop + SD Forge ROCm setup
# Usage: ansible-playbook main.yml
# Dry run: ansible-playbook main.yml --check
# Specific tags: ansible-playbook main.yml --tags "rocm,forge"

- name: Configure Ubuntu Desktop with SD Forge ROCm
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - group_vars/localhost.yml

  tasks:
    - name: Display configuration
      debug:
        msg:
          - "Configuring system for user: {{ username }}"
          - "Forge install directory: {{ forge_install_dir }}"
          - "ROCm version: {{ rocm_version }}"
      tags: always

    - name: Import base system role
      import_role:
        name: base-system
      tags: base

    - name: Import ROCm role
      import_role:
        name: rocm
      tags: rocm

    - name: Import conda role
      import_role:
        name: conda
      tags: conda

    - name: Import SD Forge ROCm role
      import_role:
        name: forge-rocm
      tags: forge

    - name: Import desktop preferences role
      import_role:
        name: desktop-preferences
      tags: desktop
      when: configure_desktop | default(true)

    - name: Final summary
      debug:
        msg:
          - "===================="
          - "Setup complete!"
          - "===================="
          - ""
          - "Next steps:"
          - "1. Reboot to ensure all changes take effect (especially ROCm)"
          - "2. Verify ROCm: rocm-smi --showproductname"
          - "3. Activate conda: conda activate {{ forge_conda_env }}"
          - "4. Launch Forge: cd {{ forge_install_dir }} && ./webui-user-rocm.sh"
          - "5. Access WebUI at: http://localhost:7860"
          - ""
          - "For troubleshooting, see: {{ forge_install_dir }}/ROCM_SETUP.md"
      tags: always
